name: cronjob

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: secret
      run: |
        echo ${{ secrets.APP_PY }} | base64 -d > app.py
        echo ${{ secrets.TOKEN }} | base64 -d > token.json
        echo ${{ secrets.CRON }} | base64 -d > cron.sh
        chmod +x ./cron.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Seoul"
    - name: run
      run: |
        sudo timedatectl set-timezone 'Asia/Seoul'
        python app.py
        ./cron.sh
