name: Python application

on:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: secret
      run: |
        echo ${{ secrets.APP_PY }} > app.py
        echo ${{ secrets.TOKEN }} > token.json
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: |
        python app.py
