name: cronjob

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: secret
      run: |
        echo ${{ secrets.APP_PY }} | base64 -d > app.py
        echo ${{ secrets.TOKEN }} | base64 -d > token.json
        echo ${{ secrets.CRON }} | base64 -d > cron.sh
        chmod +x ./cron.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      continue-on-error: true
      env: 
        TZ: 'Asia/Seoul'
      run: python app.py
    - name: trigger
      run: ./cron.sh
